### ISSUE TITLE
 The number of samples and the sum of all chunk lengths must be equal

### ISSUE THREAD

**Issue by AnandSaran** [Ahmedbadereldin/Video-Trimmer-Android#1]
While croping

FATAL EXCEPTION: pool-6-thread-1
    Process: com.adroit.timepass.dev, PID: 8509
    java.lang.AssertionError: The number of samples and the sum of all chunk lengths must be equal
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.getChunkSizes(DefaultMp4Builder.java:624)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:114)
        at com.ahmedbadereldin.videotrimmer.Utility.generateVideo(Utility.java:104)
        at com.ahmedbadereldin.videotrimmer.Utility.startTrim(Utility.java:38)
        at com.gregantech.timepass.view.createvideo.activity.VideoTrimmerActivity$trimVideo$1.execute(VideoTrimmerActivity.kt:417)
        at com.ahmedbadereldin.videotrimmer.customVideoViews.BackgroundTask$Task.run(BackgroundTask.java:197)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by asadzoobiapps** [comment]
I am getting also same error

java.lang.AssertionError: The number of samples and the sum of all chunk lengths must be equal
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.getChunkSizes(DefaultMp4Builder.java:624)
        at com.googlecode.mp4parser.authoring.builder.DefaultMp4Builder.build(DefaultMp4Builder.java:114)

**Comment by AnandSaran** [comment]
@asadzoobiapps Sorry Bro i forgot how i fixed this issue.

**Comment by asadzoobiapps** [comment]
If we give start position 0 it works.But if we give customize start position then it crash and says all chunk lengths must be equal

**Comment by Ahmedbadereldin** [comment]
Do you still have the problem? @AnandSaran @asadzoobiapps

**Comment by asadzoobiapps** [comment]
Yes @Ahmedbadereldin

**Comment by Ahmedbadereldin** [comment]
@asadzoobiapps 
I've pushed a new release now, can you try it?

**Comment by asadzoobiapps** [comment]
Definitely i will try it and come back with my feed back thanks!!

**Comment by luckymubii** [comment]
still facing when we change the start position foe trimming.
java.lang.AssertionError: The number of samples and the sum of all chunk lengths must be equal
